const products = {
  "mens-shirts": [
    {
      id: 51,
      title: "half sleeves T shirts",
      description:
        "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
      price: 23,
      discountPercentage: 12.76,
      rating: 4.26,
      stock: 132,
      brand: "Vintage Apparel",
      category: "mens-shirts",
      thumbnail: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/51/1.png",
        "https://i.dummyjson.com/data/products/51/2.jpg",
        "https://i.dummyjson.com/data/products/51/3.jpg",
        "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
      ],
    },
    {
      id: 52,
      title: "FREE FIRE T Shirt",
      description:
        "quality and professional print - It doesn't just look high quality, it is high quality.",
      price: 10,
      discountPercentage: 14.72,
      rating: 4.52,
      stock: 128,
      brand: "FREE FIRE",
      category: "mens-shirts",
      thumbnail: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/52/1.png",
        "https://i.dummyjson.com/data/products/52/2.png",
        "https://i.dummyjson.com/data/products/52/3.jpg",
        "https://i.dummyjson.com/data/products/52/4.jpg",
        "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
      ],
    },
    {
      id: 53,
      title: "printed high quality T shirts",
      description: "Brand: vintage Apparel ,Export quality",
      price: 35,
      discountPercentage: 7.54,
      rating: 4.89,
      stock: 6,
      brand: "Vintage Apparel",
      category: "mens-shirts",
      thumbnail: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/53/1.webp",
        "https://i.dummyjson.com/data/products/53/2.jpg",
        "https://i.dummyjson.com/data/products/53/3.jpg",
        "https://i.dummyjson.com/data/products/53/4.jpg",
        "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
      ],
    },
    {
      id: 54,
      title: "Pubg Printed Graphic T-Shirt",
      description:
        "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
      price: 46,
      discountPercentage: 16.44,
      rating: 4.62,
      stock: 136,
      brand: "The Warehouse",
      category: "mens-shirts",
      thumbnail: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/54/1.jpg",
        "https://i.dummyjson.com/data/products/54/2.jpg",
        "https://i.dummyjson.com/data/products/54/3.jpg",
        "https://i.dummyjson.com/data/products/54/4.jpg",
        "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
      ],
    },
    {
      id: 55,
      title: "Money Heist Printed Summer T Shirts",
      description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
      price: 66,
      discountPercentage: 15.97,
      rating: 4.9,
      stock: 122,
      brand: "The Warehouse",
      category: "mens-shirts",
      thumbnail: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/55/1.jpg",
        "https://i.dummyjson.com/data/products/55/2.webp",
        "https://i.dummyjson.com/data/products/55/3.jpg",
        "https://i.dummyjson.com/data/products/55/4.jpg",
        "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
      ],
    },
  ],
  "mens-watches": [
    {
      id: 61,
      title: "Leather Straps Wristwatch",
      description: "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
      price: 120,
      discountPercentage: 7.14,
      rating: 4.63,
      stock: 91,
      brand: "Naviforce",
      category: "mens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/61/1.jpg",
        "https://i.dummyjson.com/data/products/61/2.png",
        "https://i.dummyjson.com/data/products/61/3.jpg",
      ],
    },
    {
      id: 62,
      title: "Waterproof Leather Brand Watch",
      description:
        "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
      price: 46,
      discountPercentage: 3.15,
      rating: 4.05,
      stock: 95,
      brand: "SKMEI 9117",
      category: "mens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/62/1.jpg",
        "https://i.dummyjson.com/data/products/62/2.jpg",
      ],
    },
    {
      id: 63,
      title: "Royal Blue Premium Watch",
      description:
        "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
      price: 50,
      discountPercentage: 2.56,
      rating: 4.89,
      stock: 142,
      brand: "SKMEI 9117",
      category: "mens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/63/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/63/1.jpg",
        "https://i.dummyjson.com/data/products/63/2.jpg",
        "https://i.dummyjson.com/data/products/63/3.png",
        "https://i.dummyjson.com/data/products/63/4.jpeg",
      ],
    },
    {
      id: 64,
      title: "Leather Strap Skeleton Watch",
      description:
        "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
      price: 46,
      discountPercentage: 10.2,
      rating: 4.98,
      stock: 61,
      brand: "Strap Skeleton",
      category: "mens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/64/1.jpg",
        "https://i.dummyjson.com/data/products/64/2.webp",
        "https://i.dummyjson.com/data/products/64/3.jpg",
        "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
      ],
    },
    {
      id: 65,
      title: "Stainless Steel Wrist Watch",
      description:
        "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
      price: 47,
      discountPercentage: 17.79,
      rating: 4.79,
      stock: 94,
      brand: "Stainless",
      category: "mens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/65/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/65/1.jpg",
        "https://i.dummyjson.com/data/products/65/2.webp",
        "https://i.dummyjson.com/data/products/65/3.jpg",
        "https://i.dummyjson.com/data/products/65/4.webp",
        "https://i.dummyjson.com/data/products/65/thumbnail.webp",
      ],
    },
  ],
  "womens-dresses": [
    {
      id: 41,
      title: "NIGHT SUIT",
      description: "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
      price: 55,
      discountPercentage: 15.05,
      rating: 4.65,
      stock: 21,
      brand: "RED MICKY MOUSE..",
      category: "womens-dresses",
      thumbnail: "https://i.dummyjson.com/data/products/41/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/41/1.jpg",
        "https://i.dummyjson.com/data/products/41/2.webp",
        "https://i.dummyjson.com/data/products/41/3.jpg",
        "https://i.dummyjson.com/data/products/41/4.jpg",
        "https://i.dummyjson.com/data/products/41/thumbnail.webp",
      ],
    },
    {
      id: 42,
      title: "Stiched Kurta plus trouser",
      description:
        "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
      price: 80,
      discountPercentage: 15.37,
      rating: 4.05,
      stock: 148,
      brand: "Digital Printed",
      category: "womens-dresses",
      thumbnail: "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/42/1.png",
        "https://i.dummyjson.com/data/products/42/2.png",
        "https://i.dummyjson.com/data/products/42/3.png",
        "https://i.dummyjson.com/data/products/42/4.jpg",
        "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
      ],
    },
    {
      id: 43,
      title: "frock gold printed",
      description:
        "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
      price: 600,
      discountPercentage: 15.55,
      rating: 4.31,
      stock: 150,
      brand: "Ghazi Fabric",
      category: "womens-dresses",
      thumbnail: "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/43/1.jpg",
        "https://i.dummyjson.com/data/products/43/2.jpg",
        "https://i.dummyjson.com/data/products/43/3.jpg",
        "https://i.dummyjson.com/data/products/43/4.jpg",
        "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
      ],
    },
    {
      id: 44,
      title: "Ladies Multicolored Dress",
      description:
        "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
      price: 79,
      discountPercentage: 16.88,
      rating: 4.03,
      stock: 2,
      brand: "Ghazi Fabric",
      category: "womens-dresses",
      thumbnail: "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/44/1.jpg",
        "https://i.dummyjson.com/data/products/44/2.jpg",
        "https://i.dummyjson.com/data/products/44/3.jpg",
        "https://i.dummyjson.com/data/products/44/4.jpg",
        "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
      ],
    },
    {
      id: 45,
      title: "Malai Maxi Dress",
      description:
        "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
      price: 50,
      discountPercentage: 5.07,
      rating: 4.67,
      stock: 96,
      brand: "IELGY",
      category: "womens-dresses",
      thumbnail: "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/45/1.jpg",
        "https://i.dummyjson.com/data/products/45/2.webp",
        "https://i.dummyjson.com/data/products/45/3.jpg",
        "https://i.dummyjson.com/data/products/45/4.jpg",
        "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
      ],
    },
  ],
  groceries: [
    {
      id: 21,
      title: "- Daal Masoor 500 grams",
      description: "Fine quality Branded Product Keep in a cool and dry place",
      price: 20,
      discountPercentage: 4.81,
      rating: 4.44,
      stock: 133,
      brand: "Saaf & Khaas",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
      images: [
        "https://i.dummyjson.com/data/products/21/1.png",
        "https://i.dummyjson.com/data/products/21/2.jpg",
        "https://i.dummyjson.com/data/products/21/3.jpg",
      ],
    },
    {
      id: 22,
      title: "Elbow Macaroni - 400 gm",
      description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
      price: 14,
      discountPercentage: 15.58,
      rating: 4.57,
      stock: 146,
      brand: "Bake Parlor Big",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/22/1.jpg",
        "https://i.dummyjson.com/data/products/22/2.jpg",
        "https://i.dummyjson.com/data/products/22/3.jpg",
      ],
    },
    {
      id: 23,
      title: "Orange Essence Food Flavou",
      description:
        "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
      price: 14,
      discountPercentage: 8.04,
      rating: 4.85,
      stock: 26,
      brand: "Baking Food Items",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/23/1.jpg",
        "https://i.dummyjson.com/data/products/23/2.jpg",
        "https://i.dummyjson.com/data/products/23/3.jpg",
        "https://i.dummyjson.com/data/products/23/4.jpg",
        "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      ],
    },
    {
      id: 24,
      title: "cereals muesli fruit nuts",
      description:
        "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
      price: 46,
      discountPercentage: 16.8,
      rating: 4.94,
      stock: 113,
      brand: "fauji",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/24/1.jpg",
        "https://i.dummyjson.com/data/products/24/2.jpg",
        "https://i.dummyjson.com/data/products/24/3.jpg",
        "https://i.dummyjson.com/data/products/24/4.jpg",
        "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      ],
    },
    {
      id: 25,
      title: "Gulab Powder 50 Gram",
      description:
        "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
      price: 70,
      discountPercentage: 13.58,
      rating: 4.87,
      stock: 47,
      brand: "Dry Rose",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/25/1.png",
        "https://i.dummyjson.com/data/products/25/2.jpg",
        "https://i.dummyjson.com/data/products/25/3.png",
        "https://i.dummyjson.com/data/products/25/4.jpg",
        "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      ],
    },
  ],
  skincare: [
    {
      id: 16,
      title: "Hyaluronic Acid Serum",
      description:
        "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
      price: 19,
      discountPercentage: 13.31,
      rating: 4.83,
      stock: 110,
      brand: "L'Oreal Paris",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/16/1.png",
        "https://i.dummyjson.com/data/products/16/2.webp",
        "https://i.dummyjson.com/data/products/16/3.jpg",
        "https://i.dummyjson.com/data/products/16/4.jpg",
        "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      ],
    },
    {
      id: 17,
      title: "Tree Oil 30ml",
      description:
        "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
      price: 12,
      discountPercentage: 4.09,
      rating: 4.52,
      stock: 78,
      brand: "Hemani Tea",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/17/1.jpg",
        "https://i.dummyjson.com/data/products/17/2.jpg",
        "https://i.dummyjson.com/data/products/17/3.jpg",
        "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      ],
    },
    {
      id: 18,
      title: "Oil Free Moisturizer 100ml",
      description:
        "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
      price: 40,
      discountPercentage: 13.1,
      rating: 4.56,
      stock: 88,
      brand: "Dermive",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/18/1.jpg",
        "https://i.dummyjson.com/data/products/18/2.jpg",
        "https://i.dummyjson.com/data/products/18/3.jpg",
        "https://i.dummyjson.com/data/products/18/4.jpg",
        "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      ],
    },
    {
      id: 19,
      title: "Skin Beauty Serum.",
      description:
        "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
      price: 46,
      discountPercentage: 10.68,
      rating: 4.42,
      stock: 54,
      brand: "ROREC White Rice",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/19/1.jpg",
        "https://i.dummyjson.com/data/products/19/2.jpg",
        "https://i.dummyjson.com/data/products/19/3.png",
        "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      ],
    },
    {
      id: 20,
      title: "Freckle Treatment Cream- 15gm",
      description:
        "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
      price: 70,
      discountPercentage: 16.99,
      rating: 4.06,
      stock: 140,
      brand: "Fair & Clear",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/20/1.jpg",
        "https://i.dummyjson.com/data/products/20/2.jpg",
        "https://i.dummyjson.com/data/products/20/3.jpg",
        "https://i.dummyjson.com/data/products/20/4.jpg",
        "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      ],
    },
  ],
  "womens-watches": [
    {
      id: 66,
      title: "Steel Analog Couple Watches",
      description: "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
      price: 35,
      discountPercentage: 3.23,
      rating: 4.79,
      stock: 24,
      brand: "Eastern Watches",
      category: "womens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
      images: [Array],
    },
    {
      id: 67,
      title: "Fashion Magnetic Wrist Watch",
      description:
        "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
      price: 60,
      discountPercentage: 16.69,
      rating: 4.03,
      stock: 46,
      brand: "Eastern Watches",
      category: "womens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
      images: [Array],
    },
    {
      id: 68,
      title: "Stylish Luxury Digital Watch",
      description:
        "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
      price: 57,
      discountPercentage: 9.03,
      rating: 4.55,
      stock: 77,
      brand: "Luxury Digital",
      category: "womens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/68/thumbnail.webp",
      images: [Array],
    },
    {
      id: 69,
      title: "Golden Watch Pearls Bracelet Watch",
      description:
        "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
      price: 47,
      discountPercentage: 17.55,
      rating: 4.77,
      stock: 89,
      brand: "Watch Pearls",
      category: "womens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
      images: [Array],
    },
    {
      id: 70,
      title: "Stainless Steel Women",
      description:
        "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
      price: 35,
      discountPercentage: 8.98,
      rating: 4.08,
      stock: 111,
      brand: "Bracelet",
      category: "womens-watches",
      thumbnail: "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
      images: [Array],
    },
  ],
  furniture: [
    {
      id: 31,
      title: "Mornadi Velvet Bed",
      description:
        "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
      price: 40,
      discountPercentage: 17,
      rating: 4.16,
      stock: 140,
      brand: "Furniture Bed Set",
      category: "furniture",
      thumbnail: "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/31/1.jpg",
        "https://i.dummyjson.com/data/products/31/2.jpg",
        "https://i.dummyjson.com/data/products/31/3.jpg",
        "https://i.dummyjson.com/data/products/31/4.jpg",
        "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
      ],
    },
    {
      id: 32,
      title: "Sofa for Coffe Cafe",
      description:
        "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
      price: 50,
      discountPercentage: 15.59,
      rating: 4.74,
      stock: 30,
      brand: "Ratttan Outdoor",
      category: "furniture",
      thumbnail: "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/32/1.jpg",
        "https://i.dummyjson.com/data/products/32/2.jpg",
        "https://i.dummyjson.com/data/products/32/3.jpg",
        "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
      ],
    },
    {
      id: 33,
      title: "3 Tier Corner Shelves",
      description:
        "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
      price: 700,
      discountPercentage: 17,
      rating: 4.31,
      stock: 106,
      brand: "Kitchen Shelf",
      category: "furniture",
      thumbnail: "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/33/1.jpg",
        "https://i.dummyjson.com/data/products/33/2.jpg",
        "https://i.dummyjson.com/data/products/33/3.jpg",
        "https://i.dummyjson.com/data/products/33/4.jpg",
        "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
      ],
    },
    {
      id: 34,
      title: "Plastic Table",
      description:
        "V﻿ery good quality plastic table for multi purpose now in reasonable price",
      price: 50,
      discountPercentage: 4,
      rating: 4.01,
      stock: 136,
      brand: "Multi Purpose",
      category: "furniture",
      thumbnail: "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/34/1.jpg",
        "https://i.dummyjson.com/data/products/34/2.jpg",
        "https://i.dummyjson.com/data/products/34/3.jpg",
        "https://i.dummyjson.com/data/products/34/4.jpg",
        "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
      ],
    },
    {
      id: 35,
      title: "3 DOOR PORTABLE",
      description:
        "Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
      price: 41,
      discountPercentage: 7.98,
      rating: 4.06,
      stock: 68,
      brand: "AmnaMart",
      category: "furniture",
      thumbnail: "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/35/1.jpg",
        "https://i.dummyjson.com/data/products/35/2.jpg",
        "https://i.dummyjson.com/data/products/35/3.jpg",
        "https://i.dummyjson.com/data/products/35/4.jpg",
        "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
      ],
    },
  ],
  "womens-bags": [
    {
      id: 71,
      title: "Women Shoulder Bags",
      description:
        "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
      price: 46,
      discountPercentage: 14.65,
      rating: 4.71,
      stock: 17,
      brand: "LouisWill",
      category: "womens-bags",
      thumbnail: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/71/1.jpg",
        "https://i.dummyjson.com/data/products/71/2.jpg",
        "https://i.dummyjson.com/data/products/71/3.webp",
        "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
      ],
    },
    {
      id: 72,
      title: "Handbag For Girls",
      description:
        "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
      price: 23,
      discountPercentage: 17.5,
      rating: 4.91,
      stock: 27,
      brand: "LouisWill",
      category: "womens-bags",
      thumbnail: "https://i.dummyjson.com/data/products/72/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/72/1.jpg",
        "https://i.dummyjson.com/data/products/72/2.png",
        "https://i.dummyjson.com/data/products/72/3.webp",
        "https://i.dummyjson.com/data/products/72/4.jpg",
        "https://i.dummyjson.com/data/products/72/thumbnail.webp",
      ],
    },
    {
      id: 73,
      title: "Fancy hand clutch",
      description:
        "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
      price: 44,
      discountPercentage: 10.39,
      rating: 4.18,
      stock: 101,
      brand: "Bracelet",
      category: "womens-bags",
      thumbnail: "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/73/1.jpg",
        "https://i.dummyjson.com/data/products/73/2.webp",
        "https://i.dummyjson.com/data/products/73/3.jpg",
        "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
      ],
    },
    {
      id: 74,
      title: "Leather Hand Bag",
      description:
        "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
      price: 57,
      discountPercentage: 11.19,
      rating: 4.01,
      stock: 43,
      brand: "Copenhagen Luxe",
      category: "womens-bags",
      thumbnail: "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/74/1.jpg",
        "https://i.dummyjson.com/data/products/74/2.jpg",
        "https://i.dummyjson.com/data/products/74/3.jpg",
        "https://i.dummyjson.com/data/products/74/4.jpg",
        "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
      ],
    },
    {
      id: 75,
      title: "Seven Pocket Women Bag",
      description:
        "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
      price: 68,
      discountPercentage: 14.87,
      rating: 4.93,
      stock: 13,
      brand: "Steal Frame",
      category: "womens-bags",
      thumbnail: "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/75/1.jpg",
        "https://i.dummyjson.com/data/products/75/2.jpg",
        "https://i.dummyjson.com/data/products/75/3.jpg",
        "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
      ],
    },
  ],
};
// [
//   'mens-shirts',
//   'mens-watches',
//   'womens-dresses',
//   'groceries',
//   'skincare',
//   'womens-watches',
//   'furniture',
//   'womens-bags'
// ];

export default products;
